# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='MatrixDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UtmData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=22)),
            ],
        ),
    ]
