# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MapDate',
            new_name='map_date',
        ),
        migrations.RenameModel(
            old_name='MatrixDate',
            new_name='matrix_date',
        ),
        migrations.RenameModel(
            old_name='UtmData',
            new_name='utm_data',
        ),
    ]
